spring.application.name=ProNearby

server.port=5181

spring.datasource.url=jdbc:mysql://localhost:3306/ProNearbytask?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JWT Secret Key
jwt.secret=a183f15d226c9e15d5c28f000026b861cebff238e4e4a265e0ac018ca5448b9ed5017e9f5bc1df227248599ea8fb06938ddb78950574414007c323eeb8164a73

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mamatahc55@gmail.com
spring.mail.password=wxvqcpqxvijltjwc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


